### ISSUE TITLE
How-to buildbuild Roadie ?

### ISSUE THREAD

**Issue by Zardoz89** [mattkimber/roadie#1]
A simple how-to build Roadie. Specially for the guys that never tuched Go.
I managed to build cargopositor, gorender and purchaser (And thanks that there is a github action to build gorender). But I really not have idea how do that with Roadie. I tried with `go build -v ./src/cmd/roadie/main.go` and I get this error : 

`src/cmd/roadie/main.go:4:2: package dto is not in GOROOT (/usr/lib/go-1.17/src/dto)`

**Comment by mattkimber** [comment]
This was pretty broken... it's from the days when Go modules were pretty new and most of the advice was to mess around with GOPATH.

I've updated it with a basic module definition and some build instructions which should work a bit better (and in general, be a bit more idiomatic Go)
